FROM python:3.13

USER root

RUN echo "===> Creating /app dir ..." \
     && mkdir -p /app \
     && chmod -R ag+w /app

RUN useradd -ms /bin/bash appuser

#--------------> install java + Connect

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components,/etc/kafka-connect/jars/"

RUN apt-get update && \
    apt-get install -y openjdk-21-jre-headless lsb-release iputils-ping nano && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
#ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
#RUN export JAVA_HOME

RUN mkdir -p /etc/apt/keyrings && \
    wget -qO - https://packages.confluent.io/deb/8.1/archive.key | gpg \
    --dearmor | tee /etc/apt/keyrings/confluent.gpg > /dev/null

RUN echo "Types: deb \n\
URIs: https://packages.confluent.io/deb/8.1 \n\
Suites: bookworm \n\
Components: main \n\
Architectures: $(dpkg --print-architecture) \n\
Signed-by: /etc/apt/keyrings/confluent.gpg \n\
" | tee /etc/apt/sources.list.d/confluent-platform.sources > /dev/null

# removed: $(lsb_release -cs) from client/Suites line
# removed: clients source

# RUN apt-get update && apt-get install confluent-platform

COPY confluent-kafka_8.1.0-1_all.deb .
RUN apt install ./confluent-kafka_8.1.0-1_all.deb

#--------------> python env

ENV PIP_DEFAULT_TIMEOUT=100 \
    # Allow statements and log messages to immediately appear
    PYTHONUNBUFFERED=1 \
    # disable a pip version check to reduce run-time & log-spam
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    # cache is useless in docker image, so disable to reduce image size
    PIP_NO_CACHE_DIR=1

RUN python3 -m ensurepip --upgrade \
  && pip3 install --no-cache --upgrade pip setuptools wheel virtualenv

ENV VIRTUAL_ENV=/tmp/venv313
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements.txt .
RUN pip install -r requirements.txt

USER appuser

# COPY confluent-pytools-0.3.1-jar-with-dependencies.jar /etc/kafka-connect/jars/
COPY confluent-pytools-0.3.1-jar-with-dependencies.jar /usr/share/java
# /usr/share/java default in connect properties
COPY *.py /app/
COPY requirements.txt /app/
COPY *.json /app/

USER root

###########################################################
# 3 ways to provide Kafka Connect properties to the worker:
###########################################################
# 1: provide env vars below
# 2: or use a mix of ENV VARS below and properties that you add to connector.properties.tpl
# format for env vars = (1) prefix with CONNECT_ (2) use _ to separate elements
# --> CONNECT_BOOTSTRAP_SERVERS becomes bootstrap.servers

ENV CONNECT_BOOTSTRAP_SERVERS=localhost:29092

RUN python3 app/env_to_props.py app/connector.properties.tpl  /etc/kafka/connect.properties

# 3: provide your own file and uncomment the following line
# COPY connect.properties /etc/kafka/connect.properties

CMD ["sleep", "infinity"]
# CMD ["/usr/bin/connect-distribute", "/etc/kafka/connect.properties"]